### ISSUE TITLE
Appropriate thresholds for taxonomic annotation of viruses.

### ISSUE THREAD

**Issue by MengzhiJ** [faylward/viralrecall#11]
Hi, 
I would like to know the appropriate threshold (min score and minvog) that I should set to mine the signal of giant viruses from many viral contigs. Thank you!

**Comment by faylward** [comment]
Sorry for my slow reply. I would recommend binning the contigs first and then running viralrecall on the bins. If you find a bin with mostly positive scores, and with NCLDV marker genes present, you can be confident that it is a draft NCLDV genome.
