### ISSUE TITLE
How to get the score of entire bin just like the result in your essay

### ISSUE THREAD

**Issue by Achuan-2** [faylward/viralrecall#13]
I have some bins. And I want to use viralrecall to screen them.
The ideal output could be a csv(tsv), one column for the MAG, one column for scores. 
I want to ask how to get the score of entire bin just like the result in your essay
![image](https://user-images.githubusercontent.com/60436214/145022436-2ebb7cdc-7617-4395-99dc-623331273f9b.png)
And I don't understand the parameter "-c"
it also retrun many replicons
![image](https://user-images.githubusercontent.com/60436214/145022703-2343bbe3-1cc0-4d75-9936-374ce1c5c789.png)

**Comment by faylward** [comment]
The -c option provides contig-level statistics (not bin). The figure shows contig-level stats too, it's just that some genomes have only 1 contig (1 replicon). If you wanted bin-level stats you would need to post-process the data to average the score for each contig in a bin.

**Comment by faylward** [comment]
The purpose of the -c option is to identify contigs with low scores that may not be viral (and should therefore be excluded from the bin).

**Comment by Achuan-2** [comment]
> The -c option provides contig-level statistics (not bin). The figure shows contig-level stats too, it's just that some genomes have only 1 contig (1 replicon). If you wanted bin-level stats you would need to post-process the data to average the score for each contig in a bin.

ok ，thanks a lot. So the cut-off for mean score of  bin should be set to >1 ?

**Comment by faylward** [comment]
I would look at the scores for each contig individually- if a contig has a very low score (<0) you may want to exclude it from your bin.
