### ISSUE TITLE
Something wrong about python-----TypeError: concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by ZongzhiWu** [faylward/viralrecall#14]
My python version:
``Python 3.5.6``
The command that has been run:
``python viralrecall.py -i examples/arm29B.fna -p test_outdir -t 2 -f``
The output file did not generate the seven files in the README, only the following four files:
``test_outdir.faa``
``test_outdir.markerout``
``test_outdir.pfamout``
``test_outdir.vogout``
Error is as follows:
``Traceback (most recent call last):``
  ``File "viralrecall.py", line 733, in <module>``
    ``status = main()``
  ``File "viralrecall.py", line 728, in main``
    ``run_program(input, project, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)``
  ``File "viralrecall.py", line 401, in run_program``
    ``df = pandas.concat([df, s1], axis=1, sort=True)``
``TypeError: concat() got an unexpected keyword argument 'sort'``

**Comment by faylward** [comment]
This looks like a pandas issue- the syntax for that module is different for different versions unfortunately. Please try a newer version of Python and let me know if the issue persists.

**Comment by ZongzhiWu** [comment]
Thanks a lot, this problem have been solved after changing the version of Python several days ago.
