### ISSUE TITLE
Assigning taxonomy on NCLDVs? The missing link.

### ISSUE THREAD

**Issue by JSSaini** [faylward/viralrecall#15]
I have obtained hundreds of promising NCLDV genomes from the Lake Cadagno metagenomics dataset.  However, I am struggling in assigning taxonomy to them. There are missing names in the "spreadsheet of annotated genomes" which are present in the GVDB databases. 
https://faylward.github.io/GVDB/

Please suggest some steps/script for assigning taxonomy on prospective NCLDV genomes. Thank you.

**Comment by faylward** [comment]
Thanks for your interest! It sounds like you have some very interesting data. 
Just to make sure we are talking about the same thing, to assign taxonomy confidently it is necessary to bin contigs and get draft genomes. Assigning taxonomy to contigs individually is very difficult- some are very short and lack marker genes, for example. There are many ways to do binning- simple tools like MetaBat2 actually do a fairly good job, but there are other alternatives (see https://merenlab.org/2022/01/03/giant-viruses/). 

If you already have bins/genomes, then I would recommend making a phylogeny using ncldv_markersearch with your 
genomes together with references (https://github.com/faylward/ncldv_markersearch). The default options of this tool use 7 marker genes to make the concatenated alignment, and you can then use IQ-TREE to make the final tree. 

As for the GVDB- please give me an example of a virus that is missing. Please note that some viruses with aberrant phylogenetic placement ("rogue taxa") were removed.

**Comment by JSSaini** [comment]
Thanks for your prompt reply. Yes, I followed the customized binning using MetaBat2 as mentioned in (https://www.nature.com/articles/s41586-020-1957-x#Sec2). Then I obtained promising NCLDV genomes by following quality assessment through ViralRecall (score > 1).  After collecting all the promising (score>1) NCLDV genomes from the Lake Cadgano water column, I used dRep to get only representative/unique genomes (n=153). 
Respecting your suggestions, it seems like I am at the phylogeny step and thanks a lot for sharing the ncldv_markersearch script. :)

**Comment by JSSaini** [comment]
The ncldv_markersearch script worked perfectly and yielded the alignment file for the tree. Please let me know where I can find reference NCLDV genomes so I can add these along? A reduced set would be great. Thank you.

**Comment by Achuan-2** [comment]
> Thanks for your prompt reply. Yes, I followed the customized binning using MetaBat2 as mentioned in (https://www.nature.com/articles/s41586-020-1957-x#Sec2). Then I obtained promising NCLDV genomes by following quality assessment through ViralRecall (score > 1). After collecting all the promising (score>1) NCLDV genomes from the Lake Cadgano water column, I used dRep to get only representative/unique genomes (n=153). Respecting your suggestions, it seems like I am at the phylogeny step and thanks a lot for sharing the ncldv_markersearch script. :)

hello，can I ask how you get promising (score>1) NCLDV genomes , score >1 for contig or whole bin? do you use viralrecall "--minscore 1" parameter or use "-c" and then filter all contigs that score >1

**Comment by JSSaini** [comment]
I used -c flag first and then considered the mean score of all contigs for each bin. Mean score (>1) for each bin was considered potentially as NCLDV.

**Comment by Achuan-2** [comment]
> I used -c flag first and then considered the mean score of all contigs for each bin. Mean score (>1) for each bin was considered potentially as NCLDV.

thanks a lot , did you filter contigs that score <0 ? Because I use viralrecall to try to recover NCLDV from gut metagenome, but can't find a bin statisfy mean score >1

**Comment by faylward** [comment]
I wouldn't be surprised if there are no NCLDV bins in an animal gut metagenome- I've surveyed quite a few gut metagenomes and they typically don't have many NCLDV (most of the viruses I pick up are Caudovirales). You could manually check a few borderline cases just to be sure, but unless you have another reason to think that NCLDV should be present then there may not be any.

**Comment by JSSaini** [comment]
> 
I calculated the scores on all contigs (-c flag) of each bin. And then imported the ViralRecall output inside R and then calculated the mean score per bin.

**Comment by Achuan-2** [comment]
I got it, thank you both very much!
