### ISSUE TITLE
NCLDV database 

### ISSUE THREAD

**Issue by slaperriere** [faylward/viralrecall#2]
Hello, 

I am getting an error when trying to run viralrecall using the NCLDV database. The general database seems to be OK. The error is: 

```
Error: File existence/permissions problem in trying to open HMM file hmm/pfam.for_ncvog.hmm.
HMM file hmm/pfam.for_ncvog.hmm not found (nor an .h3m binary of it)
```
I have hmm/NCVOG.hmm. Any idea what could be causing this problem? 

Thank you, 
Sarah

**Comment by faylward** [comment]
There seems to have been an issue with the HMM tar.gz download. I uploaded new HMMs so please try again with these. 
-Frank

**Comment by slaperriere** [comment]
It is working now! Thank you!
