### ISSUE TITLE
download from the Virginia Tech library system is not working

### ISSUE THREAD

**Issue by avkermanov** [faylward/viralrecall#4]
This problem is not related to the code, but the database is not available:
https://data.lib.vt.edu/downloads/6h440s637

**Comment by faylward** [comment]
Apologies- the site is undergoing maintenance. I put them up on Zenodo in the meantime: https://zenodo.org/record/4710691#.YIGl9hIpAUE
You should be able to download with "wget -O hmm.tar.gz https://zenodo.org/record/4710691/files/hmm.tar.gz?download=1"

**Comment by avkermanov** [comment]
That was really fast. And it works this way. Thank you very much!
