### ISSUE TITLE
/usr/bin/env: ‘python\r’: No such file or directory

### ISSUE THREAD

**Issue by KrisKieft** [faylward/viralrecall#7]
Hi,

I want to point out a simple issue that I resolved. I am on a Linux machine running Ubuntu and the python script is interpreting "\n" characters as "\r" and causing issues. I resolved the issue by replacing the characters with sed.

`sed -i 's/\r/\n/' viralrecall.py`

**Comment by faylward** [comment]
Thanks for pointing that out. I haven't seen that before, and I generally use it on either Ubuntu or centOS.
